version: "3.8"
services:
  sportzone.api:
    build:
      context: .
      dockerfile: SportZoneServer.API/Dockerfile
    ports:
      - "5000:80"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
